### ISSUE TITLE
[Question] Will ONgDB support multiple databases

### ISSUE THREAD

**Issue by KienPM** [graphstackio/ongdb-legacy-3.x#1]
Thank you for your great project.
Can you tell me will ONgDB support multiple databases at 4.x version and when 4.x version will be released

Thank you so much!

**Comment by jmsuhy** [comment]
GraphStack GDB 4.x is almost ready and it has multi database functionality.   I believe ONgDB will be adopting it in their 2.x branch from what I’ve heard.

This repo is for the legacy ONGDB versions.  

I expect 4.x of our GraphStack Neo4j fork to be ready soon.  Keep checking the main Graphstackio GitHub page.

**Comment by KienPM** [comment]
Thank you!
